# Generated by Django 5.2.8 on 2025-11-19 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0006_alter_store_tags_allow_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='原料名稱')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='類別')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='數量')),
                ('unit', models.CharField(choices=[('kg', '公斤'), ('g', '公克'), ('l', '公升'), ('ml', '毫升'), ('piece', '個'), ('pack', '包'), ('box', '箱')], default='kg', max_length=20, verbose_name='單位')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='單價')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='供應商')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最低庫存量')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='stores.store', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '原物料',
                'verbose_name_plural': '原物料',
                'db_table': 'ingredients',
                'ordering': ['-created_at'],
            },
        ),
    ]
