# Generated by Django 5.2.7 on 2025-12-10 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0014_store_stores_stor_is_publ_e1a787_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_type', models.CharField(choices=[('personalized', '個人化推播'), ('product', '餐品推播'), ('surplus', '惜福品推播'), ('loyalty', '會員優惠推播'), ('general', '一般通知')], max_length=20, verbose_name='推播類型')),
                ('title', models.CharField(max_length=255, verbose_name='推播標題')),
                ('message_content', models.TextField(verbose_name='訊息內容')),
                ('image_url', models.URLField(blank=True, verbose_name='圖片網址')),
                ('target_users', models.JSONField(default=list, help_text='LINE User ID 列表', verbose_name='目標用戶')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('scheduled', '已排程'), ('sent', '已發送'), ('failed', '發送失敗')], default='draft', max_length=20, verbose_name='狀態')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='排程時間')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='發送時間')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='接收人數')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功發送數')),
                ('failure_count', models.IntegerField(default=0, verbose_name='失敗發送數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcast_messages', to='stores.store', verbose_name='發送店家')),
            ],
            options={
                'verbose_name': '推播訊息',
                'verbose_name_plural': '推播訊息',
                'db_table': 'broadcast_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LineUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=255, unique=True, verbose_name='LINE User ID')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='LINE 顯示名稱')),
                ('picture_url', models.URLField(blank=True, verbose_name='LINE 頭像')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='綁定時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_binding', to=settings.AUTH_USER_MODEL, verbose_name='系統用戶')),
            ],
            options={
                'verbose_name': 'LINE 用戶綁定',
                'verbose_name_plural': 'LINE 用戶綁定',
                'db_table': 'line_user_bindings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='客戶可能詢問的問題', verbose_name='問題')),
                ('answer', models.TextField(help_text='對應的答案', verbose_name='回答')),
                ('keywords', models.JSONField(blank=True, default=list, help_text='用於匹配的關鍵字列表，例如：["營業時間", "幾點開", "幾點關"]', verbose_name='關鍵字')),
                ('priority', models.IntegerField(default=0, help_text='數字越大優先級越高', verbose_name='優先順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('usage_count', models.IntegerField(default=0, help_text='此 FAQ 被觸發的次數', verbose_name='使用次數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='stores.store', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '店家 FAQ',
                'verbose_name_plural': '店家 FAQ',
                'db_table': 'store_faqs',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=255, verbose_name='LINE User ID')),
                ('sender_type', models.CharField(choices=[('user', '用戶'), ('bot', '機器人')], max_length=10, verbose_name='發送者類型')),
                ('message_type', models.CharField(choices=[('text', '文字'), ('image', '圖片'), ('sticker', '貼圖'), ('location', '位置'), ('other', '其他')], default='text', max_length=20, verbose_name='訊息類型')),
                ('message_content', models.TextField(verbose_name='訊息內容')),
                ('reply_token', models.CharField(blank=True, max_length=255, verbose_name='Reply Token')),
                ('used_ai', models.BooleanField(default=False, verbose_name='使用 AI 回覆')),
                ('ai_model', models.CharField(blank=True, help_text='例如：gpt-4, gemini-pro', max_length=50, verbose_name='AI 模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_conversations', to='stores.store', verbose_name='相關店家')),
                ('matched_faq', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_logs', to='line_bot.storefaq', verbose_name='匹配的 FAQ')),
            ],
            options={
                'verbose_name': '對話記錄',
                'verbose_name_plural': '對話記錄',
                'db_table': 'conversation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreLineBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_channel_access_token', models.CharField(blank=True, help_text='從 LINE Developers Console 取得', max_length=500, verbose_name='LINE Channel Access Token')),
                ('line_channel_secret', models.CharField(blank=True, help_text='從 LINE Developers Console 取得', max_length=255, verbose_name='LINE Channel Secret')),
                ('ai_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT')], default='gemini', max_length=20, verbose_name='AI 服務提供商')),
                ('ai_api_key', models.CharField(blank=True, help_text='Google AI Studio 或 OpenAI API Key', max_length=500, verbose_name='AI API Key')),
                ('ai_model', models.CharField(default='gemini-1.5-flash', help_text='例如: gemini-1.5-flash, gemini-1.5-pro, gpt-4o-mini', max_length=100, verbose_name='AI 模型')),
                ('ai_temperature', models.FloatField(default=0.7, help_text='控制回覆的隨機性，0-1之間，越高越隨機', verbose_name='AI 溫度參數')),
                ('ai_max_tokens', models.IntegerField(default=500, help_text='限制 AI 回覆的長度', verbose_name='最大 Token 數')),
                ('custom_system_prompt', models.TextField(blank=True, help_text='留空則使用預設提示詞', verbose_name='自訂系統提示詞')),
                ('enable_ai_reply', models.BooleanField(default=True, help_text='關閉後只使用 FAQ 匹配', verbose_name='啟用 AI 智能回覆')),
                ('enable_conversation_history', models.BooleanField(default=True, help_text='AI 是否參考先前的對話內容', verbose_name='啟用對話歷史')),
                ('is_active', models.BooleanField(default=False, help_text='設定完成後啟用', verbose_name='啟用 LINE BOT')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_bot_config', to='stores.store', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '店家 LINE BOT 配置',
                'verbose_name_plural': '店家 LINE BOT 配置',
                'db_table': 'store_line_bot_configs',
            },
        ),
        migrations.AddIndex(
            model_name='storefaq',
            index=models.Index(fields=['store', 'is_active'], name='store_faqs_store_i_ca44c0_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationlog',
            index=models.Index(fields=['line_user_id', '-created_at'], name='conversatio_line_us_624083_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationlog',
            index=models.Index(fields=['store', '-created_at'], name='conversatio_store_i_ea110b_idx'),
        ),
    ]
