# Generated by Django 5.2.9 on 2025-12-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationlog',
            name='ai_model',
            field=models.CharField(blank=True, default='', help_text='例如：gpt-4, gemini-pro', max_length=50, null=True, verbose_name='AI 模型'),
        ),
    ]
