# Generated by Django 5.2.9 on 2025-12-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0002_alter_conversationlog_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelinebotconfig',
            name='welcome_message',
            field=models.TextField(blank=True, default='', help_text='用戶加入好友時自動發送的歡迎訊息，留空則使用預設訊息', verbose_name='加入好友歡迎訊息'),
        ),
    ]
