# Generated by Django 5.2.7 on 2025-12-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0003_add_welcome_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storelinebotconfig',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='Google AI Studio、OpenAI 或 Groq API Key', max_length=500, verbose_name='AI API Key'),
        ),
        migrations.AlterField(
            model_name='storelinebotconfig',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('groq', 'Groq')], default='gemini', max_length=20, verbose_name='AI 服務提供商'),
        ),
    ]
