# Generated by Django 5.2.7 on 2025-12-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0004_alter_storelinebotconfig_ai_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storelinebotconfig',
            name='ai_api_key',
        ),
        migrations.RemoveField(
            model_name='storelinebotconfig',
            name='ai_max_tokens',
        ),
        migrations.RemoveField(
            model_name='storelinebotconfig',
            name='ai_model',
        ),
        migrations.RemoveField(
            model_name='storelinebotconfig',
            name='ai_provider',
        ),
        migrations.RemoveField(
            model_name='storelinebotconfig',
            name='ai_temperature',
        ),
        migrations.AddField(
            model_name='storelinebotconfig',
            name='invitation_url',
            field=models.URLField(blank=True, help_text='從 LINE Official Account Manager 取得的操作權限邀請網址', max_length=500, verbose_name='操作權限邀請網址'),
        ),
    ]
