# Generated by Django 5.2.7 on 2025-12-25 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0005_remove_storelinebotconfig_ai_api_key_and_more'),
        ('users', '0010_merge_normalize_and_remove_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantLineBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=255, unique=True, verbose_name='LINE User ID')),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='LINE 顯示名稱')),
                ('picture_url', models.URLField(blank=True, verbose_name='LINE 頭像')),
                ('notify_schedule', models.BooleanField(default=True, help_text='是否接收排班相關通知', verbose_name='排班通知')),
                ('notify_analytics', models.BooleanField(default=True, help_text='是否接收營運分析報告', verbose_name='營運分析')),
                ('notify_inventory', models.BooleanField(default=True, help_text='是否接收原物料不足提醒', verbose_name='原物料不足')),
                ('notify_order_alert', models.BooleanField(default=True, help_text='是否接收訂單異常警報', verbose_name='訂單異常')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='綁定時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_binding', to='users.merchant', verbose_name='店家')),
            ],
            options={
                'verbose_name': '店家 LINE 綁定',
                'verbose_name_plural': '店家 LINE 綁定',
                'db_table': 'merchant_line_bindings',
                'ordering': ['-created_at'],
            },
        ),
    ]
