# Generated by Django 5.2.7 on 2025-12-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0006_merchantlinebinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuserbinding',
            name='current_mode',
            field=models.CharField(choices=[('customer', '顧客模式'), ('merchant', '店家模式')], default='customer', help_text='用於 LINE BOT 切換顯示顧客或店家資訊', max_length=20, verbose_name='當前模式'),
        ),
    ]
