# Generated by Django 5.2.9 on 2026-01-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0007_lineuserbinding_current_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelinebotconfig',
            name='broadcast_default_days_inactive',
            field=models.IntegerField(default=0, help_text='個人化推播預設的閒置天數篩選', verbose_name='預設閒置天數'),
        ),
        migrations.AddField(
            model_name='storelinebotconfig',
            name='broadcast_default_message',
            field=models.TextField(blank=True, default='', help_text='個人化推播預設的訊息內容', verbose_name='預設推播訊息'),
        ),
        migrations.AddField(
            model_name='storelinebotconfig',
            name='broadcast_default_tags',
            field=models.JSONField(blank=True, default=list, help_text='個人化推播預設選擇的食物標籤', verbose_name='預設推播標籤'),
        ),
    ]
