# Generated by Django 5.2.9 on 2026-01-04 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0008_add_broadcast_defaults'),
        ('stores', '0015_store_line_friend_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBroadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_type', models.CharField(choices=[('store_recommendation', '店家推薦'), ('new_store', '新店上架'), ('platform_announcement', '平台公告')], default='store_recommendation', max_length=30, verbose_name='推播類型')),
                ('title', models.CharField(max_length=255, verbose_name='推播標題')),
                ('message_content', models.TextField(verbose_name='訊息內容')),
                ('image_url', models.URLField(blank=True, verbose_name='圖片網址')),
                ('target_all', models.BooleanField(default=True, help_text='啟用時發送給所有已綁定 LINE 的用戶', verbose_name='發送給全體用戶')),
                ('target_users', models.JSONField(blank=True, default=list, help_text='指定的 LINE User ID 列表（target_all 為 False 時使用）', verbose_name='目標用戶')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('scheduled', '已排程'), ('sent', '已發送'), ('failed', '發送失敗')], default='draft', max_length=20, verbose_name='狀態')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='排程時間')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='發送時間')),
                ('recipient_count', models.IntegerField(default=0, verbose_name='接收人數')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功發送數')),
                ('failure_count', models.IntegerField(default=0, verbose_name='失敗發送數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='建立者')),
                ('recommended_stores', models.ManyToManyField(blank=True, related_name='platform_broadcasts', to='stores.store', verbose_name='推薦店家')),
            ],
            options={
                'verbose_name': '平台推播',
                'verbose_name_plural': '平台推播',
                'db_table': 'platform_broadcasts',
                'ordering': ['-created_at'],
            },
        ),
    ]
