# Generated by Django 5.2.9 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0009_add_platform_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineuserbinding',
            name='notify_personalized_recommendation',
            field=models.BooleanField(default=True, help_text='是否接收個人化推薦類型的推播訊息', verbose_name='個人化推薦通知'),
        ),
        migrations.AddField(
            model_name='lineuserbinding',
            name='notify_transactional_notifications',
            field=models.BooleanField(default=True, help_text='是否接收訂單進度與可取餐等交易型通知', verbose_name='交易通知'),
        ),
    ]
