# Generated by Django 5.2.9 on 2026-04-22

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('line_bot', '0010_lineuserbinding_notification_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelinebotconfig',
            name='enable_new_product_recommendation_push',
            field=models.BooleanField(default=True, help_text='關閉後不發送新品相似推薦通知。', verbose_name='啟用新品相似推薦推播'),
        ),
        migrations.AddField(
            model_name='storelinebotconfig',
            name='enable_popular_recommendation_push',
            field=models.BooleanField(default=True, help_text='關閉後不自動發送店家熱門推薦。', verbose_name='啟用店家熱門推薦推播'),
        ),
        migrations.AddField(
            model_name='storelinebotconfig',
            name='popular_recommendation_min_interval_minutes',
            field=models.IntegerField(blank=True, help_text='未填寫時，回退使用平台推薦最小間隔。', null=True, verbose_name='店家熱門推薦最小間隔（分鐘）'),
        ),
        migrations.AddField(
            model_name='storelinebotconfig',
            name='popular_recommendation_weekly_limit',
            field=models.IntegerField(blank=True, help_text='未填寫時，回退使用平台推薦每週上限。', null=True, verbose_name='店家熱門推薦每週上限'),
        ),
        migrations.AddField(
            model_name='storelinebotconfig',
            name='use_platform_recommendation_frequency',
            field=models.BooleanField(default=True, help_text='啟用時使用平台設定的最小間隔與每週上限。', verbose_name='沿用平台推播頻率'),
        ),
        migrations.CreateModel(
            name='StoreUserPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(db_index=True, max_length=255, verbose_name='LINE User ID')),
                ('push_type', models.CharField(choices=[('store_popular', '店家熱門推薦'), ('store_new_product', '店家新品推薦')], max_length=30, verbose_name='推播類型')),
                ('status', models.CharField(choices=[('success', '成功'), ('skipped', '略過'), ('failed', '失敗')], max_length=20, verbose_name='狀態')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='原因')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('product_ids', models.JSONField(blank=True, default=list, verbose_name='相關新品 ID 清單')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_push_logs', to='stores.store', verbose_name='店家')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_user_push_logs', to=settings.AUTH_USER_MODEL, verbose_name='系統用戶')),
            ],
            options={
                'verbose_name': '店家對用戶推播記錄',
                'verbose_name_plural': '店家對用戶推播記錄',
                'db_table': 'store_user_push_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='storeuserpushlog',
            index=models.Index(fields=['store', 'user', 'push_type', 'created_at'], name='store_user__store_i_f8b43a_idx'),
        ),
        migrations.AddIndex(
            model_name='storeuserpushlog',
            index=models.Index(fields=['line_user_id', 'push_type', 'created_at'], name='store_user__line_us_8ee500_idx'),
        ),
        migrations.AddIndex(
            model_name='storeuserpushlog',
            index=models.Index(fields=['push_type', 'status', 'created_at'], name='store_user__push_ty_2dbfc5_idx'),
        ),
    ]
