# Generated by Django 5.2.7 on 2026-04-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0011_storelinebotconfig_frequency_and_storeuserpushlog'),
        ('loyalty', '0003_platformcoupon_userplatformcoupon'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storeuserpushlog',
            new_name='store_user__store_i_c32cf8_idx',
            old_name='store_user__store_i_f8b43a_idx',
        ),
        migrations.RenameIndex(
            model_name='storeuserpushlog',
            new_name='store_user__line_us_11acb3_idx',
            old_name='store_user__line_us_8ee500_idx',
        ),
        migrations.RenameIndex(
            model_name='storeuserpushlog',
            new_name='store_user__push_ty_06742f_idx',
            old_name='store_user__push_ty_2dbfc5_idx',
        ),
        migrations.AddField(
            model_name='platformbroadcast',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_broadcasts', to='loyalty.platformcoupon', verbose_name='關聯優惠券'),
        ),
        migrations.AlterField(
            model_name='platformbroadcast',
            name='broadcast_type',
            field=models.CharField(choices=[('store_recommendation', '店家推薦'), ('new_store', '新店上架'), ('platform_announcement', '平台公告'), ('promotion', '平台優惠')], default='store_recommendation', max_length=30, verbose_name='推播類型'),
        ),
    ]
