# Generated by Django 5.2.7 on 2025-11-15 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0006_alter_store_tags_allow_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(help_text='系統自動生成的唯一訂位編號', max_length=20, unique=True, verbose_name='訂位編號')),
                ('customer_name', models.CharField(max_length=100, verbose_name='訂位人姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='訂位人手機')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='訂位人Email')),
                ('customer_gender', models.CharField(blank=True, help_text='male, female, other, prefer_not_to_say', max_length=20, verbose_name='訂位人性別')),
                ('reservation_date', models.DateField(verbose_name='訂位日期')),
                ('time_slot', models.CharField(help_text='例如: 18:00-20:00', max_length=20, verbose_name='訂位時段')),
                ('party_size', models.PositiveIntegerField(verbose_name='訂位人數（成人）')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='孩童人數')),
                ('special_requests', models.TextField(blank=True, verbose_name='特殊需求')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('completed', '已完成'), ('cancelled', '已取消'), ('no_show', '未到場')], default='pending', max_length=20, verbose_name='訂位狀態')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='取消時間')),
                ('cancelled_by', models.CharField(blank=True, help_text='customer 或 merchant', max_length=20, verbose_name='取消者')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='取消原因')),
                ('phone_hash', models.CharField(blank=True, help_text='用於訪客驗證身份', max_length=255, verbose_name='手機號碼雜湊')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='stores.store', verbose_name='店家')),
                ('user', models.ForeignKey(blank=True, help_text='如果為 null 則為訪客訂位', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '訂位',
                'verbose_name_plural': '訂位列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(help_text='customer, merchant, system', max_length=20, verbose_name='變更者')),
                ('change_type', models.CharField(help_text='created, updated, cancelled, confirmed, completed', max_length=20, verbose_name='變更類型')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='變更前數據')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='變更後數據')),
                ('note', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='變更時間')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='reservations.reservation', verbose_name='訂位')),
            ],
            options={
                'verbose_name': '訂位變更記錄',
                'verbose_name_plural': '訂位變更記錄列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_reservation_enabled', models.BooleanField(default=True, verbose_name='啟用訂位功能')),
                ('min_party_size', models.PositiveIntegerField(default=1, verbose_name='最少訂位人數')),
                ('max_party_size', models.PositiveIntegerField(default=20, verbose_name='最多訂位人數')),
                ('advance_booking_days', models.PositiveIntegerField(default=30, verbose_name='可提前預訂天數')),
                ('min_advance_hours', models.PositiveIntegerField(default=2, verbose_name='最少提前預訂小時數')),
                ('available_time_slots', models.JSONField(default=dict, help_text='格式: {"monday": ["11:00-13:00", "17:00-21:00"], ...}', verbose_name='可訂位時段')),
                ('slot_duration_minutes', models.PositiveIntegerField(default=120, verbose_name='每個時段時長（分鐘）')),
                ('auto_confirm', models.BooleanField(default=False, help_text='若關閉，訂位需商家手動確認', verbose_name='自動確認訂位')),
                ('send_confirmation_email', models.BooleanField(default=True, verbose_name='發送確認Email')),
                ('send_reminder_sms', models.BooleanField(default=False, verbose_name='發送提醒簡訊')),
                ('reminder_hours_before', models.PositiveIntegerField(default=24, verbose_name='提前多少小時提醒')),
                ('allow_customer_cancel', models.BooleanField(default=True, verbose_name='允許顧客取消')),
                ('cancel_hours_before', models.PositiveIntegerField(default=2, verbose_name='取消須提前多少小時')),
                ('blocked_dates', models.JSONField(default=list, help_text='格式: ["2025-12-25", "2025-01-01"]', verbose_name='封鎖日期')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_settings', to='stores.store', verbose_name='店家')),
            ],
            options={
                'verbose_name': '店家訂位設定',
                'verbose_name_plural': '店家訂位設定列表',
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_number'], name='reservation_reserva_3144d8_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['customer_phone'], name='reservation_custome_f5a4d1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['reservation_date', 'status'], name='reservation_reserva_4f8570_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['store', 'reservation_date'], name='reservation_store_i_0e6dc9_idx'),
        ),
    ]
