# Generated by Django 5.2.7 on 2025-11-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('stores', '0006_alter_store_tags_allow_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', '星期一'), ('tuesday', '星期二'), ('wednesday', '星期三'), ('thursday', '星期四'), ('friday', '星期五'), ('saturday', '星期六'), ('sunday', '星期日')], max_length=10, verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('max_capacity', models.PositiveIntegerField(help_text='此時段可容納的最大人數', verbose_name='人數上限')),
                ('max_party_size', models.PositiveIntegerField(default=10, help_text='單筆訂位可接受的最多人數', verbose_name='單筆訂位最多人數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='stores.store', verbose_name='店家')),
            ],
            options={
                'verbose_name': '訂位時段',
                'verbose_name_plural': '訂位時段列表',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('store', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
