# Generated by Django 5.2.7 on 2025-11-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_timeslot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='結束時間'),
        ),
    ]
