# Generated by Django 5.2.7 on 2025-11-15 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_timeslot_end_time'),
        ('stores', '0006_alter_store_tags_allow_null'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('store', 'day_of_week', 'start_time')},
        ),
    ]
