# Generated by Django 5.2.7 on 2025-11-15 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_timeslot_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreReservationSettings',
        ),
    ]
