# Generated by Django 5.2.7 on 2026-04-16 18:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_table_label_and_merchant_note'),
        ('stores', '0017_rename_stores_stor_is_publ_55d005_idx_stores_stor_is_publ_83fcd9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['store', 'created_at'], name='reservation_store_i_69fde1_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['store', 'status', 'reservation_date'], name='reservation_store_i_a078a8_idx'),
        ),
    ]
