# Generated by Django 5.2.9 on 2026-05-31 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservation_reservation_store_i_69fde1_idx_and_more'),
        ('stores', '0018_store_surplus_cumulative_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInSeating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_label', models.CharField(max_length=100)),
                ('party_name', models.CharField(blank=True, default='', max_length=100)),
                ('party_size', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released')], default='active', max_length=20)),
                ('seated_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_walk_in_seatings', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_in_seatings', to='stores.store')),
            ],
            options={
                'ordering': ['-seated_at'],
                'indexes': [models.Index(fields=['store', 'status', 'seated_at'], name='reservation_store_i_64e748_idx'), models.Index(fields=['store', 'table_label', 'status'], name='reservation_store_i_e7b4f4_idx')],
            },
        ),
    ]
