# Generated by Django 5.2.7 on 2026-06-04 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_walkinseating'),
        ('stores', '0018_store_surplus_cumulative_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='walkinseating',
            name='waiting_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='walkinseating',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('released', 'Released')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='walkinseating',
            name='table_label',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='walkinseating',
            index=models.Index(fields=['store', 'waiting_number', 'seated_at'], name='reservation_store_i_2b1a47_idx'),
        ),
    ]
