# Generated by Django 5.2.7 on 2025-10-21 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='merchant_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('company_account', models.CharField(max_length=8, unique=True, verbose_name='公司統編')),
            ],
        ),
    ]
