# Generated by Django 5.2.7 on 2025-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='plan',
            field=models.CharField(blank=True, choices=[('basic', '基本方案'), ('premium', '進階方案'), ('enterprise', '企業方案')], max_length=20, null=True, verbose_name='付費方案'),
        ),
    ]
