# Generated by Django 5.2.7 on 2025-11-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merchant_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('prefer_not_to_say', '不提供')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', help_text='用於外送、帳單等用途'),
        ),
    ]
