# Generated by Django 5.2.9 on 2025-12-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_gender_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='discount_reason',
            field=models.TextField(blank=True, default='', help_text='管理員記錄給予折扣的原因', verbose_name='折扣原因'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='platform_fee_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='管理員設定的平台費折扣百分比，0-100之間', max_digits=5, verbose_name='平台費折扣(%)'),
        ),
    ]
