# Generated by Django 5.2.9 on 2025-12-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merchant_discount_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_id', models.CharField(help_text='公司統一編號', max_length=8, unique=True, verbose_name='公司統編')),
                ('name', models.CharField(help_text='公司名稱', max_length=255, verbose_name='公司名稱')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company_tax_id',
            field=models.CharField(blank=True, help_text='選填，如果填寫且對應到某間公司，則代表是該公司員工', max_length=8, null=True, verbose_name='公司統編'),
        ),
    ]
