# Generated by Django 5.2.7 on 2025-12-14 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merchant_discount_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder_name', models.CharField(max_length=100, verbose_name='持卡人姓名')),
                ('card_number_encrypted', models.BinaryField(verbose_name='加密的卡號')),
                ('card_last_four', models.CharField(max_length=4, verbose_name='卡號後四碼')),
                ('expiry_month', models.CharField(max_length=2, verbose_name='到期月份')),
                ('expiry_year', models.CharField(max_length=4, verbose_name='到期年份')),
                ('cvv_encrypted', models.BinaryField(verbose_name='加密的CVV')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否為預設卡片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '信用卡',
                'verbose_name_plural': '信用卡',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
