# Generated by Django 5.2.9 on 2025-12-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('groq', 'Groq')], default='gemini', max_length=20, verbose_name='AI 提供商')),
                ('ai_api_key', models.CharField(blank=True, help_text='由平台管理員設定，供所有店家使用', max_length=500, verbose_name='AI API Key')),
                ('ai_model', models.CharField(default='gemini-2.5-flash', help_text='例如: gemini-2.5-flash, gpt-4o-mini, llama-3.3-70b-versatile', max_length=100, verbose_name='AI 模型')),
                ('ai_temperature', models.FloatField(default=0.7, help_text='控制回覆的隨機性，0-1之間', verbose_name='AI 溫度參數')),
                ('ai_max_tokens', models.IntegerField(default=500, help_text='限制 AI 回覆的長度', verbose_name='最大 Token 數')),
                ('is_ai_enabled', models.BooleanField(default=True, help_text='關閉後所有店家的 AI 回覆功能將停用', verbose_name='啟用 AI 服務')),
                ('default_system_prompt', models.TextField(blank=True, default='', help_text='所有店家 AI 回覆的預設提示詞，店家可自訂覆蓋', verbose_name='預設系統提示詞')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('updated_by', models.CharField(blank=True, max_length=100, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '平台設定',
                'verbose_name_plural': '平台設定',
                'db_table': 'platform_settings',
            },
        ),
    ]
