# Generated by Django 5.2.7 on 2025-12-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='is_line_bot_enabled',
            field=models.BooleanField(default=False, help_text='開啟後平台可發送推播訊息給用戶', verbose_name='啟用平台 LINE BOT'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='line_bot_channel_access_token',
            field=models.CharField(blank=True, help_text='平台 LINE Messaging API 的 Access Token', max_length=500, verbose_name='LINE BOT Channel Access Token'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='line_bot_channel_secret',
            field=models.CharField(blank=True, help_text='平台 LINE Messaging API 的 Channel Secret', max_length=255, verbose_name='LINE BOT Channel Secret'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='line_bot_welcome_message',
            field=models.TextField(blank=True, default='歡迎使用 DineVerse！我可以為您推薦美食店家。', verbose_name='LINE BOT 歡迎訊息'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='line_login_channel_id',
            field=models.CharField(blank=True, help_text='從 LINE Developers Console 取得', max_length=100, verbose_name='LINE Login Channel ID'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='line_login_channel_secret',
            field=models.CharField(blank=True, help_text='從 LINE Developers Console 取得', max_length=255, verbose_name='LINE Login Channel Secret'),
        ),
    ]
