# Generated by Django 5.2.9 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0002_platformsettings_is_line_bot_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='personalized_recommendation_min_interval_minutes',
            field=models.IntegerField(default=4320, help_text='同一用戶兩次個人化推薦推播之間的最小間隔。預設 4320 分鐘（72 小時）。', verbose_name='個人化推薦最小間隔（分鐘）'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='personalized_recommendation_weekly_limit',
            field=models.IntegerField(default=2, help_text='同一用戶每 7 天最多接收的個人化推薦推播次數。', verbose_name='個人化推薦每週上限'),
        ),
    ]
