# Generated by Django 5.2.9 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0003_platformsettings_recommendation_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='is_personalized_recommendation_enabled',
            field=models.BooleanField(default=True, help_text='開啟後會根據用戶訂單行為發送個人化店家推薦。', verbose_name='啟用個人化推薦'),
        ),
    ]
