# Generated by Django 5.2.9 on 2026-04-22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intelligence', '0004_platformsettings_enable_personalized_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalizedRecommendationPushLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(db_index=True, max_length=255, verbose_name='LINE User ID')),
                ('push_type', models.CharField(choices=[('personalized', '個人化推薦'), ('popular', '熱門推薦'), ('fallback', '備援推薦')], max_length=30, verbose_name='推播類型')),
                ('status', models.CharField(choices=[('success', '成功'), ('skipped', '略過'), ('failed', '失敗')], max_length=20, verbose_name='狀態')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='原因')),
                ('error_message', models.TextField(blank=True, verbose_name='錯誤訊息')),
                ('recommended_store_ids', models.JSONField(blank=True, default=list, verbose_name='推薦店家 ID 清單')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='personalized_recommendation_push_logs', to=settings.AUTH_USER_MODEL, verbose_name='系統用戶')),
            ],
            options={
                'verbose_name': '個人化推薦推播記錄',
                'verbose_name_plural': '個人化推薦推播記錄',
                'db_table': 'personalized_recommendation_push_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='personalizedrecommendationpushlog',
            index=models.Index(fields=['user', 'push_type', 'created_at'], name='personalized_user_id_4a2669_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizedrecommendationpushlog',
            index=models.Index(fields=['line_user_id', 'created_at'], name='personalized_line_us_4e4f94_idx'),
        ),
        migrations.AddIndex(
            model_name='personalizedrecommendationpushlog',
            index=models.Index(fields=['push_type', 'status', 'created_at'], name='personalized_push_ty_54a365_idx'),
        ),
    ]
