# Generated by Django 5.2.9 on 2026-04-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0005_personalizedrecommendationpushlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='personalizedrecommendationpushlog',
            new_name='personalize_user_id_683c04_idx',
            old_name='personalized_user_id_4a2669_idx',
        ),
        migrations.RenameIndex(
            model_name='personalizedrecommendationpushlog',
            new_name='personalize_line_us_4ae6bb_idx',
            old_name='personalized_line_us_4e4f94_idx',
        ),
        migrations.RenameIndex(
            model_name='personalizedrecommendationpushlog',
            new_name='personalize_push_ty_7afb64_idx',
            old_name='personalized_push_ty_54a365_idx',
        ),
    ]
