# Generated by Django 5.2.7 on 2025-12-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoutorder',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('accepted', '已接受'), ('in_progress', '待完成'), ('completed', '已完成'), ('rejected', '已拒絕')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='takeoutorder',
            name='use_utensils',
            field=models.BooleanField(default=False),
        ),
    ]
