# Generated by Django 5.2.7 on 2025-12-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_takeoutorder_status_takeoutorder_use_utensils'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoutorder',
            name='service_channel',
            field=models.CharField(choices=[('takeout', '外帶'), ('dine_in', '內用')], default='takeout', max_length=20),
        ),
        migrations.AddField(
            model_name='takeoutorder',
            name='table_label',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='takeoutorder',
            name='use_eco_tableware',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
