# Generated by Django 5.2.7 on 2025-12-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_takeoutorder_service_channel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeoutorder',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('accepted', '已接受'), ('ready_for_pickup', '可取餐'), ('completed', '已完成'), ('rejected', '已拒絕')], default='pending', max_length=20),
        ),
    ]
