# Generated by Django 5.2.7 on 2025-12-07 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_takeoutorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takeoutorder',
            options={'ordering': ['-created_at'], 'verbose_name': '外帶/內用訂單', 'verbose_name_plural': '外帶/內用訂單'},
        ),
        migrations.AddField(
            model_name='takeoutorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AddField(
            model_name='takeoutorder',
            name='user',
            field=models.ForeignKey(blank=True, help_text='如果是會員下單則記錄用戶資訊', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeout_orders', to=settings.AUTH_USER_MODEL, verbose_name='會員'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='customer_name',
            field=models.CharField(max_length=50, verbose_name='顧客姓名'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='顧客電話'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', '現金'), ('credit_card', '信用卡'), ('line_pay', 'LINE Pay')], max_length=20, verbose_name='付款方式'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='pickup_at',
            field=models.DateTimeField(verbose_name='取餐時間'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='pickup_number',
            field=models.CharField(max_length=10, unique=True, verbose_name='取單號碼'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='service_channel',
            field=models.CharField(choices=[('takeout', '外帶'), ('dine_in', '內用')], default='takeout', max_length=20, verbose_name='服務類型'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('accepted', '已接受'), ('ready_for_pickup', '可取餐'), ('completed', '已完成'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='訂單狀態'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='table_label',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='桌號'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='use_eco_tableware',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='使用環保餐具'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='use_utensils',
            field=models.BooleanField(default=False, verbose_name='需要餐具'),
        ),
    ]
