# Generated by Django 5.2.7 on 2025-12-07 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_takeoutorder_options_takeoutorder_updated_at_and_more'),
        ('products', '0006_remove_takeoutorderitem_order_and_more'),
        ('stores', '0013_alter_store_cuisine_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takeoutorder',
            options={'ordering': ['-created_at'], 'verbose_name': '外帶訂單', 'verbose_name_plural': '外帶訂單'},
        ),
        migrations.AlterModelOptions(
            name='takeoutorderitem',
            options={'verbose_name': '外帶訂單項目', 'verbose_name_plural': '外帶訂單項目'},
        ),
        migrations.RemoveField(
            model_name='takeoutorder',
            name='service_channel',
        ),
        migrations.RemoveField(
            model_name='takeoutorder',
            name='table_label',
        ),
        migrations.RemoveField(
            model_name='takeoutorder',
            name='use_eco_tableware',
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeout_orders', to='stores.store', verbose_name='店家'),
        ),
        migrations.AlterField(
            model_name='takeoutorder',
            name='user',
            field=models.ForeignKey(blank=True, help_text='如果是會員下單則記錄用戶資訊', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_takeout_orders', to=settings.AUTH_USER_MODEL, verbose_name='會員'),
        ),
        migrations.AlterField(
            model_name='takeoutorderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.takeoutorder', verbose_name='訂單'),
        ),
        migrations.AlterField(
            model_name='takeoutorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeout_order_items', to='products.product', verbose_name='商品'),
        ),
        migrations.AlterField(
            model_name='takeoutorderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='數量'),
        ),
        migrations.CreateModel(
            name='DineInOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(help_text='通常為桌號', max_length=50, verbose_name='顧客姓名')),
                ('customer_phone', models.CharField(default='0000000000', max_length=20, verbose_name='顧客電話')),
                ('table_label', models.CharField(max_length=20, verbose_name='桌號')),
                ('payment_method', models.CharField(choices=[('cash', '現金'), ('credit_card', '信用卡'), ('line_pay', 'LINE Pay')], max_length=20, verbose_name='付款方式')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('order_number', models.CharField(max_length=10, unique=True, verbose_name='訂單號碼')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('accepted', '已接受'), ('preparing', '準備中'), ('ready', '已完成'), ('completed', '已送達'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='訂單狀態')),
                ('use_eco_tableware', models.BooleanField(default=False, verbose_name='使用環保餐具')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinein_orders', to='stores.store', verbose_name='店家')),
                ('user', models.ForeignKey(blank=True, help_text='如果是會員下單則記錄用戶資訊', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_dinein_orders', to=settings.AUTH_USER_MODEL, verbose_name='會員')),
            ],
            options={
                'verbose_name': '內用訂單',
                'verbose_name_plural': '內用訂單',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DineInOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='數量')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.dineinorder', verbose_name='訂單')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinein_order_items', to='products.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '內用訂單項目',
                'verbose_name_plural': '內用訂單項目',
            },
        ),
    ]
