# Generated by Django 6.0 on 2025-12-11 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0006_alter_takeoutorder_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('message', models.TextField(verbose_name='內容')),
                ('notification_type', models.CharField(choices=[('order_status', '訂單狀態更新'), ('system', '系統通知')], default='order_status', max_length=20, verbose_name='通知類型')),
                ('is_read', models.BooleanField(default=False, verbose_name='已讀')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order_number', models.CharField(blank=True, max_length=50, verbose_name='訂單號碼')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
