# Generated by Django 5.2.7 on 2025-12-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineinorderitem',
            name='specifications',
            field=models.JSONField(blank=True, default=list, help_text='儲存已選規格的 JSON 資料', verbose_name='規格選擇'),
        ),
        migrations.AddField(
            model_name='dineinorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='含規格調整後的單價', max_digits=10, null=True, verbose_name='單價'),
        ),
        migrations.AddField(
            model_name='takeoutorderitem',
            name='specifications',
            field=models.JSONField(blank=True, default=list, help_text='儲存已選規格的 JSON 資料，如 [{"groupName": "大小", "optionName": "大份", "priceAdjustment": 20}]', verbose_name='規格選擇'),
        ),
        migrations.AddField(
            model_name='takeoutorderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='含規格調整後的單價', max_digits=10, null=True, verbose_name='單價'),
        ),
    ]
