# Generated by Django 5.2.7 on 2025-12-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_specifications_to_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineinorder',
            name='product_redemptions',
            field=models.JSONField(blank=True, default=list, help_text='儲存綠色點數兌換的免費商品資訊', verbose_name='兌換商品'),
        ),
        migrations.AddField(
            model_name='takeoutorder',
            name='product_redemptions',
            field=models.JSONField(blank=True, default=list, help_text='儲存綠色點數兌換的免費商品資訊', verbose_name='兌換商品'),
        ),
        migrations.AlterField(
            model_name='dineinorder',
            name='status',
            field=models.CharField(choices=[('pending', '待處理'), ('accepted', '已接受'), ('preparing', '準備中'), ('ready', '已完成'), ('ready_for_pickup', '可取餐'), ('completed', '已送達'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='訂單狀態'),
        ),
    ]
