# Generated by Django 5.2.7 on 2026-04-16 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0011_order_item_product_snapshot'),
        ('stores', '0017_rename_stores_stor_is_publ_55d005_idx_stores_stor_is_publ_83fcd9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['store', 'status', 'created_at'], name='orders_dine_store_i_cf7d7a_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['store', 'created_at'], name='orders_dine_store_i_d3dcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['user', 'created_at'], name='orders_dine_user_id_a4e126_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['customer_phone', 'created_at'], name='orders_dine_custome_a5294f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='orders_noti_user_id_a39d62_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='orders_noti_user_id_d4d32c_idx'),
        ),
        migrations.AddIndex(
            model_name='takeoutorder',
            index=models.Index(fields=['store', 'status', 'created_at'], name='orders_take_store_i_74aa54_idx'),
        ),
        migrations.AddIndex(
            model_name='takeoutorder',
            index=models.Index(fields=['store', 'created_at'], name='orders_take_store_i_a9f03e_idx'),
        ),
        migrations.AddIndex(
            model_name='takeoutorder',
            index=models.Index(fields=['user', 'created_at'], name='orders_take_user_id_71358a_idx'),
        ),
        migrations.AddIndex(
            model_name='takeoutorder',
            index=models.Index(fields=['customer_phone', 'created_at'], name='orders_take_custome_fbd8ed_idx'),
        ),
    ]
