# Generated by Django 5.2.7 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_dineinorder_orders_dine_store_i_cf7d7a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoutorder',
            name='is_hidden_from_merchant',
            field=models.BooleanField(db_index=True, default=False, verbose_name='商家端已隱藏'),
        ),
        migrations.AddField(
            model_name='dineinorder',
            name='is_hidden_from_merchant',
            field=models.BooleanField(db_index=True, default=False, verbose_name='商家端已隱藏'),
        ),
    ]
