# Generated by Django 5.2.7 on 2026-04-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_takeoutorder_is_hidden_from_merchant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeoutorder',
            name='is_hidden_from_customer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='顧客端已隱藏'),
        ),
        migrations.AddField(
            model_name='dineinorder',
            name='is_hidden_from_customer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='顧客端已隱藏'),
        ),
    ]
