# Generated by Django 5.2.7 on 2026-04-16 17:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_takeoutorder_is_hidden_from_customer_and_more'),
        ('stores', '0017_rename_stores_stor_is_publ_55d005_idx_stores_stor_is_publ_83fcd9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['store', 'is_hidden_from_merchant', 'created_at'], name='orders_dine_store_i_90ab3f_idx'),
        ),
        migrations.AddIndex(
            model_name='dineinorder',
            index=models.Index(fields=['store', 'is_hidden_from_merchant', 'status', 'created_at'], name='orders_dine_store_i_87fba6_idx'),
        ),
        migrations.AddIndex(
            model_name='takeoutorder',
            index=models.Index(fields=['store', 'is_hidden_from_merchant', 'created_at'], name='orders_take_store_i_d020f1_idx'),
        ),
        migrations.AddIndex(
            model_name='takeoutorder',
            index=models.Index(fields=['store', 'is_hidden_from_merchant', 'status', 'created_at'], name='orders_take_store_i_73ca9b_idx'),
        ),
    ]
