# Generated by Django 5.2.9 on 2025-12-13 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        ('stores', '0014_store_stores_stor_is_publ_e1a787_idx_and_more'),
        ('users', '0009_company_user_company_tax_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeScheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('shift_type', models.CharField(choices=[('morning', '早班'), ('noon', '午班'), ('evening', '晚班')], max_length=20, verbose_name='時段類型')),
                ('role', models.CharField(max_length=100, verbose_name='職務')),
                ('notes', models.TextField(blank=True, default='', help_text='員工填寫的備註說明', verbose_name='備註')),
                ('week_start_date', models.DateField(help_text='該申請所屬的週（週一日期）', verbose_name='週起始日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('company', models.ForeignKey(help_text='員工所屬的公司', on_delete=django.db.models.deletion.CASCADE, related_name='employee_requests', to='users.company', verbose_name='所屬公司')),
                ('employee', models.ForeignKey(help_text='申請排班的員工', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_requests', to=settings.AUTH_USER_MODEL, verbose_name='員工')),
                ('store', models.ForeignKey(help_text='申請排班的店家', on_delete=django.db.models.deletion.CASCADE, related_name='employee_schedule_requests', to='stores.store', verbose_name='申請店家')),
            ],
            options={
                'verbose_name': '員工排班申請',
                'verbose_name_plural': '員工排班申請',
                'db_table': 'employee_schedule_requests',
                'ordering': ['-week_start_date', 'date', 'shift_type'],
                'unique_together': {('employee', 'store', 'date', 'shift_type', 'week_start_date')},
            },
        ),
    ]
