# Generated by Django 5.2.9 on 2025-12-10 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.ForeignKey(blank=True, help_text='如果員工需要登入系統，請關聯使用者帳號', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='關聯使用者帳號'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('ready', '準備就緒'), ('ongoing', '進行中'), ('pending', '待排班'), ('applied', '已申請')], default='pending', max_length=20, verbose_name='狀態'),
        ),
        migrations.CreateModel(
            name='ShiftApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('approved', '已確認'), ('rejected', '已拒絕')], default='pending', max_length=20, verbose_name='申請狀態')),
                ('message', models.TextField(blank=True, default='', help_text='員工可以在此填寫申請理由或備註', verbose_name='申請備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審核時間')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='schedules.shift', verbose_name='排班時段')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_applications', to='schedules.staff', verbose_name='申請員工')),
            ],
            options={
                'verbose_name': '排班申請',
                'verbose_name_plural': '排班申請',
                'db_table': 'shift_applications',
                'ordering': ['-created_at'],
                'unique_together': {('shift', 'staff')},
            },
        ),
    ]
