# Generated by Django 5.2.9 on 2026-04-26 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_employee_request_off_duty_fields'),
        ('stores', '0018_store_surplus_cumulative_stats'),
        ('users', '0010_merge_normalize_and_remove_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employeeschedulerequest',
            index=models.Index(fields=['store', '-date', '-created_at'], name='employee_sc_store_i_ca39c1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedulerequest',
            index=models.Index(fields=['employee', '-date', '-created_at'], name='employee_sc_employe_6f9932_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeschedulerequest',
            index=models.Index(fields=['store', 'assignment_status', '-date'], name='employee_sc_store_i_122d59_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['store', 'date', 'start_hour', 'start_minute'], name='shifts_store_i_864b8d_idx'),
        ),
    ]
