# Generated by Django 5.2.8 on 2025-11-28 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_product_service_type'),
        ('stores', '0011_alter_store_cuisine_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurplusFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='惜福品名稱')),
                ('description', models.TextField(blank=True, verbose_name='商品描述')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='原價')),
                ('surplus_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='惜福價')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='可售數量')),
                ('remaining_quantity', models.PositiveIntegerField(verbose_name='剩餘數量')),
                ('condition', models.CharField(choices=[('near_expiry', '即期品'), ('surplus', '剩餘品'), ('damaged_package', '外包裝損傷'), ('end_of_day', '當日剩餘')], default='surplus', max_length=20, verbose_name='商品狀況')),
                ('expiry_date', models.DateField(blank=True, help_text='即期品必填', null=True, verbose_name='到期日')),
                ('available_from', models.DateTimeField(verbose_name='開始販售時間')),
                ('available_until', models.DateTimeField(verbose_name='結束販售時間')),
                ('image', models.ImageField(blank=True, null=True, upload_to='surplus_food_images/', verbose_name='商品圖片')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '上架中'), ('inactive', '已下架'), ('sold_out', '已售完'), ('expired', '已過期')], default='draft', max_length=20, verbose_name='狀態')),
                ('pickup_instructions', models.TextField(blank=True, help_text='例如：請於時段內到店取餐', verbose_name='取餐說明')),
                ('tags', models.JSONField(blank=True, default=list, help_text='例如：["素食", "無麩質", "環保"]', verbose_name='標籤')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='惜福品編號')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='瀏覽次數')),
                ('orders_count', models.PositiveIntegerField(default=0, verbose_name='訂購次數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='上架時間')),
                ('product', models.ForeignKey(blank=True, help_text='可選：關聯到現有商品', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_items', to='products.product', verbose_name='關聯商品')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_foods', to='stores.store', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '惜福食品',
                'verbose_name_plural': '惜福食品',
                'db_table': 'surplus_foods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurplusFoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True, verbose_name='訂單編號')),
                ('customer_name', models.CharField(max_length=100, verbose_name='顧客姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='顧客手機')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='顧客Email')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總價')),
                ('payment_method', models.CharField(choices=[('cash', '現金'), ('credit_card', '信用卡'), ('line_pay', 'LINE Pay'), ('points', '點數兌換')], max_length=20, verbose_name='付款方式')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('ready', '可取餐'), ('completed', '已完成'), ('cancelled', '已取消'), ('expired', '已過期')], default='pending', max_length=20, verbose_name='訂單狀態')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='預計取餐時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='訂單時間')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='確認時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_orders', to='stores.store', verbose_name='店家')),
                ('surplus_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='surplus_food.surplusfood', verbose_name='惜福食品')),
            ],
            options={
                'verbose_name': '惜福食品訂單',
                'verbose_name_plural': '惜福食品訂單',
                'db_table': 'surplus_food_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurplusTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：午餐惜福、晚餐惜福', max_length=100, verbose_name='時段名稱')),
                ('day_of_week', models.CharField(choices=[('monday', '星期一'), ('tuesday', '星期二'), ('wednesday', '星期三'), ('thursday', '星期四'), ('friday', '星期五'), ('saturday', '星期六'), ('sunday', '星期日')], max_length=10, verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='例如：30 代表 7折（原價的70%）', max_digits=5, verbose_name='折扣百分比')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_time_slots', to='stores.store', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '惜福時段',
                'verbose_name_plural': '惜福時段',
                'db_table': 'surplus_time_slots',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('store', 'day_of_week', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='surplusfood',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surplus_foods', to='surplus_food.surplustimeslot', verbose_name='惜福時段'),
        ),
        migrations.AddIndex(
            model_name='surplusfood',
            index=models.Index(fields=['store', 'status'], name='surplus_foo_store_i_c30211_idx'),
        ),
        migrations.AddIndex(
            model_name='surplusfood',
            index=models.Index(fields=['available_from', 'available_until'], name='surplus_foo_availab_e97c29_idx'),
        ),
    ]
