# Generated by Django 5.2.7 on 2025-11-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surplustimeslot',
            name='discount_percent',
        ),
    ]
