# Generated by Django 5.2.7 on 2025-11-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0002_remove_surplustimeslot_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surplusfood',
            name='status',
            field=models.CharField(choices=[('active', '上架中'), ('sold_out', '已售完'), ('expired', '已過期')], default='active', max_length=20, verbose_name='狀態'),
        ),
    ]
