# Generated by Django 5.2.7 on 2025-11-29 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0003_alter_surplusfood_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='surplusfood',
            name='surplus_foo_availab_e97c29_idx',
        ),
    ]
