# Generated by Django 5.2.7 on 2025-11-29 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0004_remove_surplusfood_surplus_foo_availab_e97c29_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surplusfood',
            name='available_from',
        ),
        migrations.RemoveField(
            model_name='surplusfood',
            name='available_until',
        ),
        migrations.AlterField(
            model_name='surplusfood',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surplus_foods', to='surplus_food.surplustimeslot', verbose_name='惜福時段'),
        ),
    ]
