# Generated by Django 5.2.7 on 2025-11-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0005_remove_surplusfood_available_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surplusfood',
            name='status',
            field=models.CharField(choices=[('active', '上架中'), ('inactive', '已下架'), ('sold_out', '已售完')], default='active', max_length=20, verbose_name='狀態'),
        ),
    ]
