# Generated by Django 5.2.7 on 2025-12-05 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_enable_loyalty_store_enable_reservation_and_more'),
        ('surplus_food', '0006_alter_surplusfood_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurplusFoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：麵包類、熟食類、飲料類', max_length=100, verbose_name='類別名稱')),
                ('description', models.TextField(blank=True, verbose_name='類別描述')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='數字越小越前面', verbose_name='顯示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surplus_categories', to='stores.store', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '惜福食品類別',
                'verbose_name_plural': '惜福食品類別',
                'db_table': 'surplus_food_categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.AddField(
            model_name='surplusfood',
            name='category',
            field=models.ForeignKey(blank=True, help_text='選擇此惜福品所屬的類別', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='surplus_food.surplusfoodcategory', verbose_name='惜福品類別'),
        ),
    ]
