# Generated by Django 5.2.7 on 2025-12-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0007_surplusfoodcategory_surplusfood_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfood',
            name='dining_option',
            field=models.CharField(choices=[('dine_in', '內用'), ('takeout', '外帶'), ('both', '內用和外帶')], default='both', max_length=20, verbose_name='用餐選項'),
        ),
        migrations.AlterField(
            model_name='surplusfood',
            name='condition',
            field=models.CharField(choices=[('near_expiry', '即期品'), ('surplus', '剩餘品'), ('damaged_package', '外包裝損傷')], default='surplus', max_length=20, verbose_name='商品狀況'),
        ),
    ]
