# Generated by Django 5.2.7 on 2025-12-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0008_surplusfood_dining_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfoodorder',
            name='pickup_number',
            field=models.CharField(blank=True, help_text='例如：S001, S002', max_length=10, verbose_name='取餐號碼'),
        ),
        migrations.AddField(
            model_name='surplusfoodorder',
            name='use_utensils',
            field=models.BooleanField(default=False, verbose_name='是否需要餐具'),
        ),
    ]
