# Generated by Django 5.2.9 on 2025-12-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0009_surplusfoodorder_pickup_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfoodorder',
            name='order_type',
            field=models.CharField(choices=[('dine_in', '內用'), ('takeout', '外帶')], default='takeout', help_text='內用或外帶', max_length=20, verbose_name='訂單類型'),
        ),
    ]
