# Generated by Django 5.2.9 on 2025-12-10 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0010_surplusfoodorder_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surplusfoodorder',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='surplusfoodorder',
            name='surplus_food',
        ),
        migrations.RemoveField(
            model_name='surplusfoodorder',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='surplusfoodorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='總價'),
        ),
        migrations.CreateModel(
            name='SurplusFoodOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='數量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='小計')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='surplus_food.surplusfoodorder', verbose_name='訂單')),
                ('surplus_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='surplus_food.surplusfood', verbose_name='惜福食品')),
            ],
            options={
                'verbose_name': '惜福食品訂單項目',
                'verbose_name_plural': '惜福食品訂單項目',
                'db_table': 'surplus_food_order_items',
            },
        ),
    ]
