# Generated by Django 5.2.9 on 2025-12-10 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0011_remove_surplusfoodorder_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfoodorder',
            name='table_label',
            field=models.CharField(blank=True, help_text='內用訂單的桌號', max_length=20, verbose_name='桌號'),
        ),
    ]
