# Generated by Django 6.0 on 2025-12-12 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0012_surplusfoodorder_table_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfoodorder',
            name='user',
            field=models.ForeignKey(blank=True, help_text='如果是會員下單則記錄用戶資訊', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_surplus_orders', to=settings.AUTH_USER_MODEL, verbose_name='會員'),
        ),
    ]
