# Generated by Django 5.2.9 on 2025-12-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_store_stores_stor_is_publ_e1a787_idx_and_more'),
        ('surplus_food', '0013_surplusfoodorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surplusfoodorder',
            name='status',
            field=models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('ready', '可取餐'), ('completed', '已完成'), ('cancelled', '已取消'), ('rejected', '已拒絕'), ('expired', '已過期')], default='pending', max_length=20, verbose_name='訂單狀態'),
        ),
        migrations.CreateModel(
            name='GreenPointRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('no_utensils', '外帶不要餐具'), ('own_container', '自備環保容器'), ('own_cup', '自備環保杯'), ('own_bag', '自備購物袋'), ('dine_in_eco', '內用自備環保餐具')], max_length=30, verbose_name='環保行為類型')),
                ('name', models.CharField(help_text='例如：外帶不要餐具回饋', max_length=100, verbose_name='回饋名稱')),
                ('description', models.TextField(blank=True, verbose_name='回饋說明')),
                ('points_reward', models.PositiveIntegerField(default=1, help_text='完成此環保行為可獲得的點數', verbose_name='獎勵點數')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_point_rules', to='stores.store', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '綠色點數回饋設定',
                'verbose_name_plural': '綠色點數回饋設定',
                'db_table': 'green_point_rules',
                'ordering': ['action_type'],
                'unique_together': {('store', 'action_type')},
            },
        ),
    ]
