# Generated by Django 5.2.9 on 2025-12-20 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_store_stores_stor_is_publ_e1a787_idx_and_more'),
        ('surplus_food', '0014_add_green_point_reward_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointRedemptionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：100點換9折', max_length=100, verbose_name='規則名稱')),
                ('description', models.TextField(blank=True, verbose_name='規則描述')),
                ('redemption_type', models.CharField(choices=[('discount', '折扣兌換'), ('product', '商品兌換')], default='discount', max_length=20, verbose_name='兌換類型')),
                ('required_points', models.PositiveIntegerField(help_text='兌換所需的綠色點數', verbose_name='所需點數')),
                ('discount_type', models.CharField(blank=True, choices=[('percent', '百分比折扣'), ('amount', '固定金額折扣')], max_length=20, null=True, verbose_name='折扣類型')),
                ('discount_value', models.DecimalField(blank=True, decimal_places=2, help_text='百分比或金額', max_digits=10, null=True, verbose_name='折扣值')),
                ('product_name', models.CharField(blank=True, max_length=255, verbose_name='兌換商品名稱')),
                ('product_description', models.TextField(blank=True, verbose_name='商品描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_redemption_rules', to='stores.store', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '點數兌換規則',
                'verbose_name_plural': '點數兌換規則',
                'db_table': 'point_redemption_rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
