# Generated by Django 5.2.9 on 2025-12-21 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_store_stores_stor_is_publ_e1a787_idx_and_more'),
        ('surplus_food', '0015_add_point_redemption_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GreenPointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='點數')),
                ('transaction_type', models.CharField(choices=[('earn', '獲得'), ('redeem', '兌換')], max_length=20, verbose_name='交易類型')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='原因說明')),
                ('order_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='關聯訂單ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='交易時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_point_transactions', to='stores.store', verbose_name='店家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_point_transactions', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '綠色點數交易記錄',
                'verbose_name_plural': '綠色點數交易記錄',
                'db_table': 'green_point_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserGreenPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='點數餘額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_green_points', to='stores.store', verbose_name='店家')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green_points', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '用戶綠色點數',
                'verbose_name_plural': '用戶綠色點數',
                'db_table': 'user_green_points',
                'unique_together': {('user', 'store')},
            },
        ),
    ]
