# Generated by Django 5.2.7 on 2025-12-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0016_add_user_green_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointredemptionrule',
            name='max_quantity_per_order',
            field=models.PositiveIntegerField(default=1, help_text='商品兌換時，單筆訂單最多可兌換的份數（折扣兌換固定為1）', verbose_name='單筆訂單可兌換份數'),
        ),
    ]
