# Generated by Django 5.2.7 on 2026-04-16 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_rename_stores_stor_is_publ_55d005_idx_stores_stor_is_publ_83fcd9_idx_and_more'),
        ('surplus_food', '0018_surplus_order_item_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='surplusfoodorder',
            index=models.Index(fields=['store', 'status', 'created_at'], name='surplus_foo_store_i_9957de_idx'),
        ),
        migrations.AddIndex(
            model_name='surplusfoodorder',
            index=models.Index(fields=['store', 'created_at'], name='surplus_foo_store_i_43671e_idx'),
        ),
        migrations.AddIndex(
            model_name='surplusfoodorder',
            index=models.Index(fields=['user', 'created_at'], name='surplus_foo_user_id_cd186b_idx'),
        ),
        migrations.AddIndex(
            model_name='surplusfoodorder',
            index=models.Index(fields=['customer_phone', 'created_at'], name='surplus_foo_custome_79baef_idx'),
        ),
    ]
