# Generated by Django 5.2.7 on 2026-04-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0019_surplusfoodorder_surplus_foo_store_i_9957de_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfoodorder',
            name='is_hidden_from_merchant',
            field=models.BooleanField(db_index=True, default=False, verbose_name='商家端已隱藏'),
        ),
    ]
