# Generated by Django 5.2.7 on 2026-04-17 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0020_surplusfoodorder_is_hidden_from_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfoodorder',
            name='is_hidden_from_customer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='顧客端已隱藏'),
        ),
    ]
