# Generated by Django 5.2.9 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surplus_food', '0021_surplusfoodorder_is_hidden_from_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='surplusfoodorder',
            name='counted_in_store_surplus_stats',
            field=models.BooleanField(db_index=True, default=False, verbose_name='已計入店家惜福統計'),
        ),
    ]
