# Generated by Django 5.2.7 on 2025-11-26 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
        ('orders', '0001_initial'),
        ('stores', '0006_alter_store_tags_allow_null'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiplevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pointrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='redemptionproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CustomerLoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, help_text='歷史累積總點數')),
                ('available_points', models.IntegerField(default=0, help_text='目前可用點數')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='loyalty.membershiplevel')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_accounts', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '顧客會員帳戶',
                'verbose_name_plural': '顧客會員帳戶',
                'unique_together': {('user', 'store')},
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField(help_text='兌換時使用的點數')),
                ('status', models.CharField(choices=[('pending', '待確認'), ('confirmed', '已確認'), ('redeemed', '已兌換'), ('cancelled', '已取消'), ('expired', '已過期')], default='pending', max_length=20)),
                ('redemption_code', models.CharField(editable=False, max_length=50, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.customerloyaltyaccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='loyalty.redemptionproduct')),
            ],
            options={
                'verbose_name': '兌換記錄',
                'verbose_name_plural': '兌換記錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', '獲得'), ('redeem', '兌換使用'), ('adjust', '調整'), ('expire', '過期')], max_length=20)),
                ('points', models.IntegerField(help_text='點數變動量（正數為獲得，負數為使用）')),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loyalty.customerloyaltyaccount')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='orders.takeoutorder')),
                ('redemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_transactions', to='loyalty.redemption')),
            ],
            options={
                'verbose_name': '點數交易記錄',
                'verbose_name_plural': '點數交易記錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
