# Generated by Django 5.2.7 on 2026-04-23 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0002_alter_membershiplevel_id_alter_pointrule_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('claim_token', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('discount_type', models.CharField(choices=[('fixed', '固定金額'), ('percent', '百分比')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '平台優惠券',
                'verbose_name_plural': '平台優惠券',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPlatformCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('claimed', '已領取'), ('used', '已使用'), ('expired', '已過期')], default='claimed', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_coupons', to='loyalty.platformcoupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者平台優惠券',
                'verbose_name_plural': '使用者平台優惠券',
                'ordering': ['-claimed_at'],
                'unique_together': {('user', 'coupon')},
            },
        ),
    ]
