# Generated by Django 5.2.7 on 2025-12-14 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0007_notification'),
        ('products', '0009_remove_product_food_tags_delete_foodtag_and_more'),
        ('stores', '0014_store_stores_stor_is_publ_e1a787_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, help_text='1-5星評分')),
                ('comment', models.TextField(blank=True, help_text='文字評論')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dinein_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='orders.dineinorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='stores.store')),
                ('takeout_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='orders.takeoutorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '菜品評論',
                'verbose_name_plural': '菜品評論',
                'db_table': 'reviews_product_review',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, help_text='1-5星評分')),
                ('tags', models.JSONField(blank=True, default=list, help_text='快速標籤列表')),
                ('comment', models.TextField(blank=True, help_text='文字評論')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant_reply', models.TextField(blank=True, help_text='商家回覆')),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('dinein_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_reviews', to='orders.dineinorder')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store')),
                ('takeout_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_reviews', to='orders.takeoutorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '店家評論',
                'verbose_name_plural': '店家評論',
                'db_table': 'reviews_store_review',
                'ordering': ['-created_at'],
            },
        ),
    ]
