# Generated by Django 5.2.9 on 2026-04-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_storereviewimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_review_images/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.productreview')),
            ],
            options={
                'verbose_name': '菜品評論圖片',
                'verbose_name_plural': '菜品評論圖片',
                'db_table': 'reviews_product_review_image',
                'ordering': ['created_at'],
            },
        ),
    ]
