# Generated by Django 5.2.7 on 2025-11-08 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_merchant_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the restaurant/store.', max_length=255, verbose_name='餐廳名稱')),
                ('description', models.TextField(blank=True, help_text='A detailed description of the restaurant.', verbose_name='餐廳描述')),
                ('address', models.TextField(help_text='The address of the restaurant.', verbose_name='地址')),
                ('phone', models.CharField(help_text='The phone number of the restaurant.', max_length=20, verbose_name='電話')),
                ('email', models.EmailField(blank=True, help_text='The email address of the restaurant.', max_length=254, verbose_name='Email')),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='Opening hours for each day of the week.', verbose_name='營業時間')),
                ('is_open', models.BooleanField(default=True, help_text='Indicates if the restaurant is currently open.', verbose_name='營業狀態')),
                ('image', models.ImageField(blank=True, help_text='An image of the restaurant.', null=True, upload_to='store_images/', verbose_name='餐廳圖片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.OneToOneField(help_text='The merchant who owns this store.', on_delete=django.db.models.deletion.CASCADE, related_name='store', to='users.merchant')),
            ],
            options={
                'verbose_name': '店家資訊',
                'verbose_name_plural': '店家資訊',
            },
        ),
    ]
