# Generated by Django 5.2.7 on 2025-11-08 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='image',
        ),
        migrations.AddField(
            model_name='store',
            name='budget_banquet',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average budget for banquet.', max_digits=10, null=True, verbose_name='宴會平均預算'),
        ),
        migrations.AddField(
            model_name='store',
            name='budget_dinner',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average budget for dinner.', max_digits=10, null=True, verbose_name='晚餐平均預算'),
        ),
        migrations.AddField(
            model_name='store',
            name='budget_lunch',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average budget for lunch.', max_digits=10, null=True, verbose_name='午餐平均預算'),
        ),
        migrations.AddField(
            model_name='store',
            name='credit_cards',
            field=models.CharField(blank=True, help_text='Accepted credit cards (comma-separated).', max_length=500, verbose_name='接受的信用卡'),
        ),
        migrations.AddField(
            model_name='store',
            name='fixed_holidays',
            field=models.TextField(blank=True, help_text='Fixed holidays or maintenance days.', verbose_name='固定休息日'),
        ),
        migrations.AddField(
            model_name='store',
            name='has_english_menu',
            field=models.BooleanField(default=False, help_text='Whether the restaurant has an English menu.', verbose_name='提供英文菜單'),
        ),
        migrations.AddField(
            model_name='store',
            name='has_wifi',
            field=models.BooleanField(default=False, help_text='Whether the restaurant provides Wi-Fi.', verbose_name='提供 Wi-Fi'),
        ),
        migrations.AddField(
            model_name='store',
            name='parking_info',
            field=models.TextField(blank=True, help_text='Parking information.', verbose_name='停車場資訊'),
        ),
        migrations.AddField(
            model_name='store',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional remarks or notes.', verbose_name='備註'),
        ),
        migrations.AddField(
            model_name='store',
            name='smoking_policy',
            field=models.CharField(choices=[('no_smoking', '完全禁煙'), ('smoking_allowed', '可吸菸'), ('separate_room', '有專用吸菸室')], default='no_smoking', help_text='Smoking policy of the restaurant.', max_length=20, verbose_name='吸菸政策'),
        ),
        migrations.AddField(
            model_name='store',
            name='suitable_for_children',
            field=models.BooleanField(default=False, help_text='Whether the restaurant is suitable for children.', verbose_name='適合帶小孩'),
        ),
        migrations.AddField(
            model_name='store',
            name='transportation',
            field=models.TextField(blank=True, help_text='Transportation information to reach the restaurant.', verbose_name='交通方式'),
        ),
        migrations.AddField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True, help_text='The website URL of the restaurant.', verbose_name='餐廳網站'),
        ),
        migrations.CreateModel(
            name='StoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image of the restaurant.', upload_to='store_images/', verbose_name='圖片')),
                ('order', models.IntegerField(default=0, help_text='Order of the image (lower numbers appear first).', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(help_text='The store this image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.store')),
            ],
            options={
                'verbose_name': '餐廳圖片',
                'verbose_name_plural': '餐廳圖片',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
