# Generated by Django 5.2.7 on 2025-11-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_remove_store_image_store_budget_banquet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the store is published and visible to customers.', verbose_name='是否上架'),
        ),
    ]
