# Generated by Django 5.2.7 on 2025-11-08 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='menu_text',
            field=models.TextField(blank=True, help_text='Menu items with prices in text format.', verbose_name='菜單文字內容'),
        ),
        migrations.AddField(
            model_name='store',
            name='menu_type',
            field=models.CharField(blank=True, choices=[('text', '文字與價格'), ('image', '菜單圖片')], default='text', help_text='Type of menu display: text with prices or menu images.', max_length=10, verbose_name='菜單類型'),
        ),
        migrations.CreateModel(
            name='MenuImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='A menu image of the restaurant.', upload_to='menu_images/', verbose_name='菜單圖片')),
                ('order', models.IntegerField(default=0, help_text='Order of the menu image (lower numbers appear first).', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(help_text='The store this menu image belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='menu_images', to='stores.store')),
            ],
            options={
                'verbose_name': '菜單圖片',
                'verbose_name_plural': '菜單圖片',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
