# Generated by Django 5.2.8 on 2025-11-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_menu_text_store_menu_type_menuimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags for categorizing and searching the store (e.g., ['Italian', 'Pizza', 'Romantic']).", verbose_name='標籤'),
        ),
    ]
