# Generated by Django 5.2.7 on 2025-11-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_dine_in_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.CharField(blank=True, choices=[('japanese', '日式'), ('korean', '韓式'), ('american', '美式'), ('taiwanese', '台式'), ('western', '西式'), ('other', '其他')], help_text='The category of the restaurant.', max_length=20, verbose_name='餐廳類別'),
        ),
    ]
