# Generated by Django 5.2.7 on 2025-11-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AddField(
            model_name='store',
            name='cuisine_type',
            field=models.CharField(choices=[('japanese', '日式'), ('korean', '韓式'), ('american', '美式'), ('taiwanese', '台式'), ('western', '西式'), ('other', '其他')], default='other', help_text='The cuisine type of the restaurant.', max_length=20, verbose_name='餐廳類別'),
        ),
    ]
