# Generated by Django 5.2.7 on 2025-11-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_remove_store_category_store_cuisine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enable_loyalty',
            field=models.BooleanField(default=True, help_text='Enable or disable loyalty program feature.', verbose_name='啟用會員功能'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_reservation',
            field=models.BooleanField(default=True, help_text='Enable or disable reservation feature.', verbose_name='啟用訂位功能'),
        ),
        migrations.AddField(
            model_name='store',
            name='enable_surplus_food',
            field=models.BooleanField(default=True, help_text='Enable or disable surplus food feature.', verbose_name='啟用惜福品功能'),
        ),
    ]
