# Generated by Django 5.2.8 on 2025-11-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_tags_allow_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cuisine_type',
            field=models.CharField(choices=[('japanese', '日式'), ('korean', '韓式'), ('american', '美式'), ('taiwanese', '台式'), ('western', '西式'), ('beverages', '飲料'), ('desserts', '甜點'), ('other', '其他')], default='other', help_text='The cuisine type of the restaurant.', max_length=20, verbose_name='餐廳類別'),
        ),
    ]
