# Generated by Django 5.2.7 on 2025-12-05 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_enable_loyalty_store_enable_reservation_and_more'),
        ('stores', '0011_alter_store_cuisine_type'),
    ]

    operations = [
    ]
