# Generated by Django 5.2.9 on 2025-12-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_alter_store_cuisine_type'),
        ('users', '0007_user_gender_alter_user_address'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_published', 'cuisine_type'], name='stores_stor_is_publ_e1a787_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_published', 'enable_reservation'], name='stores_stor_is_publ_91e945_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_published', 'enable_loyalty'], name='stores_stor_is_publ_82e72f_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_published', 'enable_surplus_food'], name='stores_stor_is_publ_c009ff_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name'], name='stores_stor_name_988b60_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['created_at'], name='stores_stor_created_f1ef67_idx'),
        ),
    ]
