# Generated by Django 5.2.7 on 2025-12-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0014_store_stores_stor_is_publ_e1a787_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='line_friend_url',
            field=models.URLField(blank=True, help_text='LINE official account friend URL for customers to add.', verbose_name='LINE 好友網址'),
        ),
    ]
