# Generated by Django 5.2.7 on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_store_line_friend_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enable_takeout',
            field=models.BooleanField(
                default=True,
                help_text='Enable or disable takeout ordering feature.',
                verbose_name='啟用外帶點餐功能',
            ),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(
                fields=['is_published', 'enable_takeout'],
                name='stores_stor_is_publ_55d005_idx',
            ),
        ),
    ]
