# Generated by Django 5.2.9 on 2026-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_store_enable_takeout'),
        ('users', '0010_merge_normalize_and_remove_permissions'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='store',
            new_name='stores_stor_is_publ_83fcd9_idx',
            old_name='stores_stor_is_publ_55d005_idx',
        ),
        migrations.AddField(
            model_name='store',
            name='region',
            field=models.CharField(blank=True, choices=[('', '未選擇'), ('臺北市', '臺北市'), ('新北市', '新北市'), ('桃園市', '桃園市'), ('臺中市', '臺中市'), ('臺南市', '臺南市'), ('高雄市', '高雄市'), ('宜蘭縣', '宜蘭縣'), ('新竹縣', '新竹縣'), ('苗栗縣', '苗栗縣'), ('彰化縣', '彰化縣'), ('南投縣', '南投縣'), ('雲林縣', '雲林縣'), ('嘉義縣', '嘉義縣'), ('屏東縣', '屏東縣'), ('花蓮縣', '花蓮縣'), ('臺東縣', '臺東縣'), ('澎湖縣', '澎湖縣'), ('基隆市', '基隆市'), ('新竹市', '新竹市'), ('嘉義市', '嘉義市')], default='', help_text='Administrative region for filtering, e.g. 臺北市.', max_length=10, verbose_name='地區'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_published', 'region'], name='stores_stor_is_publ_3f7709_idx'),
        ),
    ]
