# Generated by Django 5.2.9 on 2026-04-20

from decimal import Decimal

from django.db import migrations, models
from django.db.models import Count, Sum


def backfill_surplus_cumulative_stats(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    SurplusFoodOrder = apps.get_model('surplus_food', 'SurplusFoodOrder')

    completed_orders = SurplusFoodOrder.objects.filter(status='completed')
    summary_rows = completed_orders.values('store_id').annotate(
        completed_count=Count('id'),
        completed_revenue=Sum('total_price'),
    )

    for row in summary_rows:
        Store.objects.filter(id=row['store_id']).update(
            surplus_completed_order_count_total=row['completed_count'] or 0,
            surplus_completed_revenue_total=row['completed_revenue'] or Decimal('0'),
        )

    completed_orders.filter(counted_in_store_surplus_stats=False).update(
        counted_in_store_surplus_stats=True
    )


def reset_surplus_cumulative_stats(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    SurplusFoodOrder = apps.get_model('surplus_food', 'SurplusFoodOrder')

    Store.objects.all().update(
        surplus_completed_order_count_total=0,
        surplus_completed_revenue_total=Decimal('0'),
    )
    SurplusFoodOrder.objects.all().update(counted_in_store_surplus_stats=False)


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_rename_stores_stor_is_publ_55d005_idx_stores_stor_is_publ_83fcd9_idx_and_more'),
        ('surplus_food', '0022_surplusfoodorder_counted_in_store_surplus_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='surplus_completed_order_count_total',
            field=models.PositiveIntegerField(default=0, help_text='累積完成的惜福品訂單數，不因訂單隱藏或刪除而遞減。', verbose_name='惜福品累積完成訂單數'),
        ),
        migrations.AddField(
            model_name='store',
            name='surplus_completed_revenue_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='累積完成的惜福品訂單收入，不因訂單隱藏或刪除而遞減。', max_digits=12, verbose_name='惜福品累積完成訂單收入'),
        ),
        migrations.RunPython(backfill_surplus_cumulative_stats, reset_surplus_cumulative_stats),
    ]
