# Generated by Django 5.2.7 on 2025-10-22 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='A detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the product.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='An image of the product.', null=True, upload_to='product_images/')),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if the product is available for purchase.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('merchant', models.ForeignKey(help_text='The merchant who owns this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.merchant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
