# Generated by Django 5.2.7 on 2025-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_type',
            field=models.CharField(choices=[('dine_in', '內用'), ('takeaway', '外帶'), ('both', '內用與外帶')], default='both', max_length=10),
        ),
    ]
