# Generated by Django 5.2.8 on 2025-11-21 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_service_type'),
        ('stores', '0006_alter_store_tags_allow_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store'),
            preserve_default=False,
        ),
    ]
