# Generated by Django 5.2.8 on 2025-11-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_store'),
        ('stores', '0006_alter_store_tags_allow_null'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=20)),
                ('pickup_at', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('cash', '現金'), ('credit_card', '信用卡'), ('line_pay', 'LINE Pay')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('pickup_number', models.CharField(max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_takeout_orders', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='TakeoutOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.takeoutorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_takeout_items', to='products.product')),
            ],
        ),
    ]
