# Generated by Django 5.2.9 on 2025-12-06 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_takeoutorder_takeoutorderitem'),
        ('stores', '0013_alter_store_cuisine_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：主餐、飲料、甜點', max_length=100, verbose_name='類別名稱')),
                ('description', models.TextField(blank=True, verbose_name='類別描述')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='數字越小越前面', verbose_name='顯示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='stores.store', verbose_name='所屬店家')),
            ],
            options={
                'verbose_name': '產品類別',
                'verbose_name_plural': '產品類別',
                'db_table': 'product_categories',
                'ordering': ['display_order', 'name'],
                'unique_together': {('store', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='產品類別'),
        ),
    ]
