# Generated by Django 5.2.9 on 2025-12-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productcategory_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeoutorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='takeoutorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='TakeoutOrder',
        ),
        migrations.DeleteModel(
            name='TakeoutOrderItem',
        ),
    ]
