# Generated by Django 5.2.9 on 2025-12-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_product_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：辣、甜、素食、海鮮、牛肉', max_length=50, unique=True, verbose_name='標籤名稱')),
                ('description', models.TextField(blank=True, verbose_name='標籤描述')),
                ('color', models.CharField(default='#3B82F6', help_text='十六進位色碼，例如：#FF5722', max_length=7, verbose_name='標籤顏色')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
            ],
            options={
                'verbose_name': '食物標籤',
                'verbose_name_plural': '食物標籤',
                'db_table': 'food_tags',
                'ordering': ['name'],
            },
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_store_i_d5d442_idx',
            old_name='products_store_avail_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_store_i_09c517_idx',
            old_name='products_store_service_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='products_categor_ee4b4e_idx',
            old_name='products_category_idx',
        ),
        migrations.AddField(
            model_name='product',
            name='food_tags',
            field=models.ManyToManyField(blank=True, help_text='選擇此商品的食物特性標籤，例如：辣、甜、素食等', related_name='products', to='products.foodtag', verbose_name='食物標籤'),
        ),
    ]
