# Generated by Django 5.2.9 on 2025-12-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_foodtag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='food_tags',
        ),
        migrations.DeleteModel(
            name='FoodTag',
        ),
        migrations.AddField(
            model_name='product',
            name='food_tags',
            field=models.JSONField(blank=True, default=list, help_text='輸入此商品的食物特性標籤，例如：["辣", "甜", "素食"]', verbose_name='食物標籤'),
        ),
    ]
