# Generated by Django 5.2.7 on 2025-12-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_food_tags_delete_foodtag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：大份、小份、加辣', max_length=100, verbose_name='規格名稱')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='正數為加價，負數為減價', max_digits=10, verbose_name='價格調整')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='數字越小越前面', verbose_name='顯示順序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='products.product', verbose_name='所屬商品')),
            ],
            options={
                'verbose_name': '商品規格',
                'verbose_name_plural': '商品規格',
                'db_table': 'product_specifications',
                'ordering': ['display_order', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
    ]
