# Generated by Django 5.2.7 on 2025-12-20 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_add_product_specification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['display_order', 'name'], 'verbose_name': '規格選項', 'verbose_name_plural': '規格選項'},
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(help_text='例如：大份、小份、加辣', max_length=100, verbose_name='選項名稱'),
        ),
        migrations.CreateModel(
            name='SpecificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例如：大小、配料、辣度', max_length=100, verbose_name='類別名稱')),
                ('selection_type', models.CharField(choices=[('single', '單選'), ('multiple', '多選')], default='single', help_text='單選：只能選一個；多選：可選多個', max_length=10, verbose_name='選擇類型')),
                ('is_required', models.BooleanField(default=False, help_text='是否必須選擇此類別的選項', verbose_name='必選')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='數字越小越前面', verbose_name='顯示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specification_groups', to='products.product', verbose_name='所屬商品')),
            ],
            options={
                'verbose_name': '規格類別',
                'verbose_name_plural': '規格類別',
                'db_table': 'specification_groups',
                'ordering': ['display_order', 'name'],
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productspecification',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='products.specificationgroup', verbose_name='所屬類別'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productspecification',
            unique_together={('group', 'name')},
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='product',
        ),
    ]
